/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ScamNumberService } from "../scamNumber.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ScamNumberCreateInput } from "./ScamNumberCreateInput";
import { ScamNumber } from "./ScamNumber";
import { ScamNumberFindManyArgs } from "./ScamNumberFindManyArgs";
import { ScamNumberWhereUniqueInput } from "./ScamNumberWhereUniqueInput";
import { ScamNumberUpdateInput } from "./ScamNumberUpdateInput";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { ReportWhereUniqueInput } from "../../report/base/ReportWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ScamNumberControllerBase {
  constructor(
    protected readonly service: ScamNumberService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ScamNumber })
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createScamNumber(
    @common.Body() data: ScamNumberCreateInput
  ): Promise<ScamNumber> {
    return await this.service.createScamNumber({
      data: data,
      select: {
        id: true,
        isScam: true,
        lastCheckedDate: true,
        phone: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ScamNumber] })
  @ApiNestedQuery(ScamNumberFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async scamNumbers(@common.Req() request: Request): Promise<ScamNumber[]> {
    const args = plainToClass(ScamNumberFindManyArgs, request.query);
    return this.service.scamNumbers({
      ...args,
      select: {
        id: true,
        isScam: true,
        lastCheckedDate: true,
        phone: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ScamNumber })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async scamNumber(
    @common.Param() params: ScamNumberWhereUniqueInput
  ): Promise<ScamNumber | null> {
    const result = await this.service.scamNumber({
      where: params,
      select: {
        id: true,
        isScam: true,
        lastCheckedDate: true,
        phone: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ScamNumber })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateScamNumber(
    @common.Param() params: ScamNumberWhereUniqueInput,
    @common.Body() data: ScamNumberUpdateInput
  ): Promise<ScamNumber | null> {
    try {
      return await this.service.updateScamNumber({
        where: params,
        data: data,
        select: {
          id: true,
          isScam: true,
          lastCheckedDate: true,
          phone: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ScamNumber })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteScamNumber(
    @common.Param() params: ScamNumberWhereUniqueInput
  ): Promise<ScamNumber | null> {
    try {
      return await this.service.deleteScamNumber({
        where: params,
        select: {
          id: true,
          isScam: true,
          lastCheckedDate: true,
          phone: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reports")
  @ApiNestedQuery(ReportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Report",
    action: "read",
    possession: "any",
  })
  async findReports(
    @common.Req() request: Request,
    @common.Param() params: ScamNumberWhereUniqueInput
  ): Promise<Report[]> {
    const query = plainToClass(ReportFindManyArgs, request.query);
    const results = await this.service.findReports(params.id, {
      ...query,
      select: {
        description: true,
        id: true,
        phoneNumber: true,
        reportDate: true,

        scamNumber: {
          select: {
            id: true,
          },
        },

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reports")
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "update",
    possession: "any",
  })
  async connectReports(
    @common.Param() params: ScamNumberWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reports: {
        connect: body,
      },
    };
    await this.service.updateScamNumber({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reports")
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "update",
    possession: "any",
  })
  async updateReports(
    @common.Param() params: ScamNumberWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reports: {
        set: body,
      },
    };
    await this.service.updateScamNumber({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reports")
  @nestAccessControl.UseRoles({
    resource: "ScamNumber",
    action: "update",
    possession: "any",
  })
  async disconnectReports(
    @common.Param() params: ScamNumberWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reports: {
        disconnect: body,
      },
    };
    await this.service.updateScamNumber({
      where: params,
      data,
      select: { id: true },
    });
  }
}
